[model]
name = "bart-large"
tokenizer_path = "facebook/bart-large"
model_path = "facebook/bart-large"

[preprocessor]
sep_token = '|'
cased = true

[train]

[train.training_args]
num_train_epochs = 20
per_device_eval_batch_size = 8
per_device_train_batch_size = 8
learning_rate = 1e-6
logging_steps = 256
warmup_steps = 512
save_strategy = "epoch"
evaluation_strategy = "epoch"
weight_decay = 0.01
save_total_limit = 2

[train.early_stopping]
early_stopping_patience = 4