[dataset]
train_path = "reddit-syac/train.csv"
val_path = "reddit-syac/dev.csv"
test_path = "reddit-syac/test.csv"

[model]
tokenizer_path = "allenai/unifiedqa-t5-base"
model_path = "allenai/unifiedqa-t5-base"

[preprocessor]
sep_token = '\n'
cased = false
# 0: pattern, 1: repl
regex_sub_args = ["'(.*)'", '\1']

[train]
tokenizer_path = "allenai/unifiedqa-t5-base"
model_path = "allenai/unifiedqa-t5-base"

[train.training_args]
# TODO: use arguments recommended for fine-tuning
output_dir = "./results/unifiedqa-t5-base"
num_train_epochs = 20
per_device_eval_batch_size = 32
per_device_train_batch_size = 4
warmup_steps = 500
learning_rate = 1e-4
logging_dir = "./logs/unifiedqa-t5-base-logs"
logging_steps = 50

save_strategy = "steps"
save_steps = 256
evaluation_strategy = "steps"
eval_steps = 256
# weight_decay = 0.01
optim = "adafactor"
load_best_model_at_end = true
save_total_limit = 2


[train.early_stopping]
early_stopping_patience = 4
# early_stopping_threshold = 0.001

[evaluate]
model = "qa"
model_path = 'C:\Users\Markus\Desktop\IN5960\ml\results'
dataset_type = "val"
report_path = "qa_model_report.md"
