[dataset]
train_path = "reddit-syac/train.csv"
val_path = "reddit-syac/dev.csv"
test_path = "reddit-syac/test.csv"

[model]
name = "bart-large-cnn-zero-shot"
tokenizer_path = "facebook/bart-large-cnn"
model_path = "facebook/bart-large-cnn"
train_max_input_length = 1024

[preprocessor]
sep_token = '|'
cased = true