[dataset]
train_path = "reddit-syac/train.csv"
val_path = "reddit-syac/dev.csv"
test_path = "reddit-syac/test.csv"

[model]
name = "pegasus-gigaword-zero-shot"
tokenizer_path = "google/pegasus-gigaword"
model_path = "google/pegasus-gigaword"
