[model]
name = "unifiedqa-large-zero-shot"
tokenizer_path = "t5-large"
model_path = "allenai/unifiedqa-t5-large"

[preprocessor]
sep_token = '\n'
cased = false
# 0: pattern, 1: repl
regex_sub_args = ["'(.*)'", '\1']