[dataset]
train_path = "reddit-syac/train.csv"
val_path = "reddit-syac/dev.csv"
test_path = "reddit-syac/test.csv"

[model]
name = "unifiedqa-t5-v2-small"
tokenizer_path = "t5-small"
model_path = "allenai/unifiedqa-t5-v2-small-1363200"

[preprocessor]
sep_token = '\n'
cased = false
# 0: pattern, 1: repl
regex_sub_args = ["'(.*)'", '\1']

[train]

[train.training_args]
seed = 42
num_train_epochs = 20
per_device_eval_batch_size = 32
per_device_train_batch_size = 8
warmup_steps = 500
learning_rate = 1e-4
logging_steps = 200
save_strategy = "epoch"
evaluation_strategy = "epoch"
# weight_decay = 0.01
optim = "adafactor"
save_total_limit = 2

[train.early_stopping]
early_stopping_patience = 4