[datapaths]
train_path = "../data/train_set.tsv"
val_path = "../data/val_set.tsv"
test_path = "../data/test_set.tsv"

[models]

[preprocessor]
# First instance where it might be relevant for a custom pattern
# Original model uses "Headline: " + article
sep_token = '|'
cased = false

[train]
tokenizer_path = "Michau/t5-base-en-generate-headline"
model_path = "Michau/t5-base-en-generate-headline"
metrics = ["rouge"]


[train.training_args]
# TODO: use arguments recommended for fine-tuning
output_dir = "./results/t5-base-en-generate-headline"
logging_dir = "./logs/t5-base-en-generate-headline"
num_train_epochs = 1
per_device_train_batch_size = 4
warmup_steps = 500
learning_rate = 5e-5
weight_decay = 0.01
logging_steps = 50
save_steps = 0
evaluation_strategy = "epoch"

[evaluate]
model = "tg"
model_path = 'C:/Users/Markus/Desktop/IN5960/ml/results'
dataset_type = "val"
report_path = "headline_model_report.md"
